## Take 1 - Machine Learning on Python 
* My first notebook for the "TensorFlow Developer Certificate: zero to mastery" course on Udemy


In [1]:
# Import TENSORFLOW
import tensorflow as tf
print(tf.__version__)

2.6.0


In [5]:
# Creating tensors with t.constante()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Checking the number of dimensions in the tensor (with ndim)
scalar.ndim

0

In [7]:
# Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
# Checking the dimension of thi vector
vector.ndim


1

In [14]:
# Creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [15]:
# and checking the dimension
matrix.ndim

2

In [16]:
# changing dtype in anothe matrix
amatrix = tf.constant([[10.,7.],[7.,10.],[8.,3.]],dtype=tf.float16)
amatrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  3.]], dtype=float16)>

In [17]:
# dimension continues the same
amatrix.ndim

2

In [18]:
# Creating a tensor 
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9][10,11,12]],[[13,14,15],[16,17,18]]])
tensor 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [19]:
# and the dimension is...
tensor.ndim

3

#### Now we are creating tensor with `tf.variable`

In [3]:
# Creating a tensor used before. But now with t.variable
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>)

In [4]:
# Changing one of the elements in the changeable tensor
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [6]:
# Using .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

In [7]:
# Now changing in the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'