## Take 1 - Machine Learning on Python 
* My first notebook for the "TensorFlow Developer Certificate: zero to mastery" course on Udemy
* In this notebook, we have tensorflow fundamentals


In [1]:
# Import TENSORFLOW
import tensorflow as tf
print(tf.__version__)

2.6.0


### Here we are creating tensors with `tf.constant`

In [2]:
# Creating tensors with tf.constante()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking the number of dimensions in the tensor (with ndim)
scalar.ndim

0

In [4]:
# Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Checking the dimension of thi vector
vector.ndim


1

In [6]:
# Creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
# and checking the dimension
matrix.ndim

2

In [8]:
# changing dtype in anothe matrix
amatrix = tf.constant([[10.,7.],[7.,10.],[8.,3.]],dtype=tf.float16)
amatrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  3.]], dtype=float16)>

In [9]:
# dimension continues the same
amatrix.ndim

2

In [10]:
# Creating a tensor 
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
# and the dimension is...
tensor.ndim

3

### Now we are creating tensors with `tf.variable`

In [12]:
# Creating a tensor used before. But now with t.variable
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>)

In [13]:
# Changing one of the elements in the changeable tensor
#changeable_tensor[0] = 7

In [14]:
# Using .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

In [15]:
# Now changing in the unchangeable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

### Creating random tensors

In [16]:
# Creating two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Now we are shuffling the order of the elements in a tensor

In [17]:
# Shuffle a Tensor
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [18]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Other ways to make tensors

In [19]:
# Creating a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# Creating a tensor of all zeros
tf.zeros(shape=(10,7)) 

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

In [21]:
# Turning Numpy arrays into tensorflow tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A,  shape=(2,3,4)) # have the same number of elements
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

### Getting information from a tensor
> A tensor have the following attributes to be knowed:
> * Shape (`tensor.shape`)
> * Rank (`tensor.ndim`)
> * Axis or dimension (`tensor[0]` or `tensor[:,1]`, depends what particular dimension you want)
> * Size (`tf.size(tensor)`)


In [23]:
# Creating a 4 rank tensor
tensor_4 = tf.zeros([2,3,4,5])
tensor_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
tensor_4.shape, tensor_4.ndim, tf.size(tensor_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing and expanding tensors


In [25]:
# Getting the first 2 elements of each dimension
tensor_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
# Creating a rank 2 tensor
rank_2 = tf.constant([[10,7],[3,4]])
rank_2.shape,rank_2.ndim


(TensorShape([2, 2]), 2)

In [27]:
# Getting the last element of each row in our rank 2 tensor
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [28]:
# Adding a extra dimension in a rank 2 tensor
rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [29]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

### Manipulating tensors
**Basic Operations**
`+`,`-`,`*` and `/`

In [30]:
# Addition and subtraction
tensor = tf.constant([[10,7],[3,4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [31]:
# Multiplication and division
tensor * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]])>

In [32]:
# Tensorflow built-in function
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

**Matrix Multiplication**

In [33]:
# Matrix multiplication with tf.matmul
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [34]:
# Matrix multiplication with the python @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

### Changing the datatype of a tensor

In [36]:
# Creating a new tensor with default datatype
b = tf.constant([1.7, 7.4])
b.dtype

tf.float32

In [37]:
c = tf.constant([10,7])
c.dtype

tf.int32

In [38]:
# Changing from float32 to float16
d = tf.cast(b, dtype=tf.float16)
d.dtype

tf.float16

In [39]:
# Changing from inte32 to float32
e = tf.cast(c, dtype = tf.float32)
e

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

### Aggregating tensors