## Take 1 - Machine Learning on Python 
* My first notebook for the "TensorFlow Developer Certificate: zero to mastery" course on Udemy


In [1]:
# Import TENSORFLOW
import tensorflow as tf
print(tf.__version__)

2.6.0


### Here we are creating tensors with `tf.constant`

In [8]:
# Creating tensors with tf.constante()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# Checking the number of dimensions in the tensor (with ndim)
scalar.ndim

0

In [10]:
# Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [11]:
# Checking the dimension of thi vector
vector.ndim


1

In [12]:
# Creating a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [13]:
# and checking the dimension
matrix.ndim

2

In [14]:
# changing dtype in anothe matrix
amatrix = tf.constant([[10.,7.],[7.,10.],[8.,3.]],dtype=tf.float16)
amatrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  3.]], dtype=float16)>

In [15]:
# dimension continues the same
amatrix.ndim

2

In [17]:
# Creating a tensor 
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [18]:
# and the dimension is...
tensor.ndim

3

### Now we are creating tensors with `tf.variable`

In [19]:
# Creating a tensor used before. But now with t.variable
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>)

In [26]:
# Changing one of the elements in the changeable tensor
#changeable_tensor[0] = 7

In [27]:
# Using .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

In [28]:
# Now changing in the unchangeable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

### Creating random tensors

In [25]:
# Creating two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Now we are shuffling the order of the elements in a tensor

In [30]:
# Shuffle a Tensor
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [34]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>